### ISSUE TITLE
[LAV Audio] No sound on PC when bitstreaming boxes are checked (even when not bitstreaming)

### ISSUE THREAD

**Issue by tahaa7** [Nevcairiel/LAVFilters#161] opened 2017-09-20 23:10 UTC
When all the bitstreaming boxes are checked in LAV Audio settings, there is no sound output on my computer's speakers or connected headphones when playing a media file in MPC-HC. Looking at the list of active filters in MPC-HC, I can also see that LAV Audio is not being used at all in that case (its icon appears in the tray briefly when the file is being opened, but then disappears before playback begins). The computer is not connected to any other device (at the moment). Only when I uncheck the corresponding audio format's bitstreaming box in LAV Audio settings do I get sound output to the computer speakers or headphones.

So, it is required that all the bitstreaming boxes in LAV Audio are manually unchecked whenever bitstreaming is not actually used (and then they would have to be rechecked again before using bitstreaming), even in case when the computer is not connected to any other device.

Please check this issue.

```
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.7.13 (e37826845)
    Compiler:           MSVC v19.00.24215.01
    Build date:         Jul 16 2017 18:47:17

LAV Filters:
    LAV Splitter:       0.70.2.1
    LAV Video:          0.70.2.1
    LAV Audio:          0.70.2.1
    FFmpeg compiler:    MinGW-w64 GCC 7.1.0

Operating system:
    Name:               Windows NT 10.0 (build 15063)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    GPU:                Intel(R) HD Graphics 630 (driver version: 22.20.16.4771)
```

**Comment by Nevcairiel** [comment] 2017-09-20 23:11
If you enable bitstreaming on a system without bitstreaming capability, this result is expected.
Also duplicate of #37

**Closed by Nevcairiel** 2017-09-20 23:11 UTC
