### ISSUE TITLE
HLS passthrough Twitch VODs freezing

### ISSUE THREAD

**Issue by Tharn** [Nevcairiel/LAVFilters#199] opened 2018-04-09 18:08 UTC
A change introduced at some point after LAV Filters 0.70.2.1-git (shipping with MPC-HC 1.7.13 as the last good version) makes Twitch VODs freeze regularly in MPC-HC. I'm using Streamlink set to HLS passthrough. Using LAV Filters 0.71, using MPC-HC 1.7.14-1.7.16 builds by Clsid all produce this behaviour.

The movie will freeze with plenty of packets still in the buffer, yet the player icon indiates it's still playing. MPC-HC continues to count the seconds for a while, but will often freeze and skip 10 seconds or so. Something is clearly still trying to work internally. MPC-HC may become unresponsive after a while, and trying to seek the video at this point may make it crash.

Sorry if this is a bit vague.

**Comment by Nevcairiel** [comment] 2018-04-10 17:52
Clear instructions how to reproduce this, including a URL, would greatly increase the chances of fixes. :)

**Comment by Tharn** [comment] 2018-04-11 11:54
In my case, I use Livestream Monitor, Streamlink, MPC-HC x64 with internal filters. LM can be left out; you may pass something like this to Streamlink directly:

`streamlink.exe --player-passthrough hls https://www.twitch.tv/user/v/248016900 720p60,720p30,720p,Best`

`--twitch-oauth-token XXXXXXXXXXXXX` may have to be appended, it's been a while that I used it without. Livestream Monitor can do this. Getting a token from Twitch involves authorizing apps through the website.

Streamlinkrc reads as follows - should not matter when you use passthrough though.

```
player="C:\Program Files\MPC-HC\mpc-hc64.exe"
player-no-close
rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
hls-segment-threads=2
hds-segment-threads=2
stream-segment-threads=2
ringbuffer-size=32M
default-stream=720p60,720p30,720p,best
# twitch-oauth-token=XXXXXXXXXXXXXXXXXXXXXXXXXXX
ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
```

As for reproducing it.. this is the difficult part. You'll have to leave the VOD running for a good while. It may help to pause it intermittently. Sometimes this makes the player stop filling buffer and simply stop playback after it runs out, but I'm pretty sure it also increases the likelihood of this issue happening.

**Comment by makedir** [comment] 2018-04-15 16:53
opening https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CpQDhtOktCX59K00aYCYml7GpEnbOZbe9KDhkUzjESV8EOgygURpeHdTZt5NPy4GwvJ7Ra7AIhrDUl1VtRdJXLkIjQtgy8LFw8uJUM9h_eVuVvpLht7YyZqUJIU5naOjojUwYmGDt4V3PcwdKNuCFBTCV2QD8wCIiGhQ9zC_PjNewBQOJ3zqB-vVAl9m1vQGa-x7qneCsFwrarStQ6CV11NcC6Dsis9kPMTPopXg_0Q-3M5C_p9wZze8NdAKC4MbD8hdL8cx9JPxDgBdHjJHOshmhzZw_Mj7WM_65Ty8eBz6NpE65US6laBC5fyYlA0EiPs7iXC0z40MPn03UAWxhDw2yUxJzW71q5XHY3DAkp4XAwuiIaU0UdKwnO0WA00-_RjfaKN6M5pRP6TtUMy11URtbRdS8mOxVV9ysAj26kM9vmO5MRqt6sysMQYwt8D09bhc31QoWJ7bJJ9A4vCFdypQx6imdTiDGGQ-xO3h3fLubEKely0iN50qzVzBxGUeMEcXJtPXp62Tw5c9HGpDfanjWugQZ2ASEF78G29Rxde3njcb8U51FhUaDCUBwjDyYZqM9fEwNA.m3u8 in mpc causes cpu freeze plz fix this

**Comment by clsid2** [comment] 2018-04-16 12:36
Above link is dead now. But I tried it when it was still working. It triggered an infinite loop in LAV Splitter (libavformat to be precise).

**Comment by Tharn** [comment] 2018-04-16 16:26
Probably a different issue if the stream can't even be opened.

**Comment by makedir** [comment] 2018-04-16 23:36
AAAAAAHA HAAA HAAA HAAAA VERY FUNNY VERY FUNNY-----
That was a TWITCH LIVE STREAM.  People on Twitch tend to go offline and sleep!? Unbelievable...

**Comment by Nevcairiel** [comment] 2018-04-17 00:02
So don't post links that stop working immediately after, they don't help anyone to find problems.

**Comment by makedir** [comment] 2018-04-17 00:04
Maybe dont look into tickets just days later instead? Or just generate te m3u8 links yourself for ANY online stream? Like this one for example...

https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CvQCrRXqPku-25XTFVRFnJW_0rg-trPAr6t5cUFFCsLgKRCSWQq8SQeGnOnPmty4iwVG4Z-_ZSGHFXZcFSETUceSL7qAjVYufnMU3hM8WKy9-BHQj1-_4FObPc0BjBC-WyEz80JLupnQwctkxpvUpFryp5C9oFroZvk7CT8WEtrG0MCU6f1HoDmqhdf55L9VBcdrwfNOJRFYx5H7KaZQGhPeS8Kgfx5Wnx27hOQ4N1uAf_4mvWEhe0bl0uHoBm7wCrEriBPT5a-bFyJhn6yAUnSacZTWli9K4YNSTpqYVkQMwp1j-CZSLaYfTYq3lgz4omgbH7ETe3lqo3ytRvNXELUQVGxjOf0yeM5k0UwG34UR7h7D3xPEbb2B83I6AwvRvV4ToUOTpQ4Kh2P4Y3EKsBI5F9M0xIUQem6-N-KqhUYYosthJDKCxFO0ofdrm2IoPliqmOcfWZ5a3Hyg1qKUKQsSCfqeGTZQccLLWFfCa5EZvsn16Tu6EhAR3iT-gFPHPKFBaVhSEB_oGgzy98Reu2UyTqAZF64.m3u8

**Comment by Nevcairiel** [comment] 2018-04-17 00:06
If you expect someone to work on any issue when *you* want to, you should start paying money instead of leeching on free software and being entitled about it.

**Comment by clsid2** [comment] 2018-04-17 10:28
Another way to get an URL:
Firefox + Flash Video Downloader extension. This extension lets you copy the video url to clipboard. Paste into browser to get the m3u8 file.

Pasting the url directly into MPC-HC doesn't work. Possibly due to user agent? An option to specify that in LAV Splitter would be cool. Maybe a dropdown list with a handful of common/useful values.

**Comment by Vanquo** [comment] 2018-04-18 01:36
Found an online Stream URL extraction tool https://pwn.sh/tools/getstream.html

No browser addons or streamlink needed. Just paste Twitch url in search box and you'll get m3u8 links of different qualities. Just drag and drop links into MPC-HC to start playing. 

For live streams, so as an example, Ninja a Fortnite streamer is playing right now, so copy and paste https://www.twitch.tv/ninja into extraction tool search box to get stream links. For Ninja's Past Broadcasts/VOD's, go to https://www.twitch.tv/ninja/videos/all and pick on one of the video links like https://www.twitch.tv/videos/251378457 and do the same thing to get links to m3u8.

Actually just noticed the CPU spike just before stream stops playing and freezes. So makedir's issue is actually the same as mine and Tharns or at least whatever changes made after LAVFilters-0.71 stable release is causing HLS twitch stream to freeze or CPU usage to go up causing it to freeze. 

Though it doesn't happen as soon as you open stream. Like I said before, it freezes about 10-20 seconds in on a live stream. I had a tough time replicating with recorded past broadcasts/VOD's as it takes awhile to happen. But it does happen. It's just faster and consistent to reproduce on a live stream. Point is, HLS playback for twitch is borked in some way.

LAVFilters-0.71 stable build and before = Good, plays normally.
LAVFilters-0.71.0-5 nightly and later = Bad, CPU spikes up then freezes player.

**Comment by Nevcairiel** [comment] 2018-04-18 12:39
Try with https://files.1f0.de/lavf/nightly/LAVFilters-0.71.0-32.exe, I might have found an issue that could've caused it.

**Comment by Vanquo** [comment] 2018-04-18 18:00
Tried LAVFilters-0.71.0-32, it no longer hard freezes or cpu spikes on live streams but now I just get sporadic hitching and pausing like its constantly buffering. At least now it continues to play unlike before where mpc-hc just locks up and stops playback.

VOD's seemingly plays fine but hard to tell for sure. Live streams definitely still has an issue but better than before.

**Comment by Nevcairiel** [comment] 2018-04-18 18:01
Increasing the queue can help to stabilize buffering troubles like that.

**Comment by Nevcairiel** [comment] 2018-04-18 18:52
I made another change for Live streaming, that should be available in the next nightly build in around 6 hours or so.

**Comment by Vanquo** [comment] 2018-04-19 00:57
So looking into this ffmpeg issue I found this https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=7&t=5582&sid=e0e6ba03adc472532116c6fa7fa76990 So it's not just a twitch stream problem. It's just a general HLS stream problem related with HTTPS TLS network security thingy.

Tried sample stream from https://kevingodell.github.io/streams/hls_mpegts_vod/. LAVFilters-0.71.0-5 and LAVFilters-0.71.0-32 freezes up after 10 seconds. LAVFilters-0.71 plays it fine. Hopefully that next nightly build has the fix for it.

**Comment by Nevcairiel** [comment] 2018-04-19 12:59
Here is a direct link to the latest nightly:
https://files.1f0.de/lavf/nightly/LAVFilters-0.71.0-34.exe

It greatly improves the reliability of Twitch playback for me.

**Comment by Tharn** [comment] 2018-04-20 16:33
Watched a livestream for a few hours last night, watching a VOD now. Always tough to say with imperfect FPS videos but it seems resolved.

**Comment by Tharn** [comment] 2018-04-21 15:54
Okay, I observed this twice now. Both times I paused the VOD, left it paused for >30 minutes and then came back to continue. A minute or two after I resumed, each time I witnessed a >10 sec freeze or stutter before the VOD continued. The buffer queue remained full throughout.

Hope this helps.

**Comment by Nevcairiel** [comment] 2019-02-27 18:25
I've replaced part of the network stack which resolved similar issues like this one. Hopefully this is also resolved in the next build.

**Closed by Nevcairiel** 2019-02-27 18:25 UTC
Labels: ffmpeg, splitter
