### ISSUE TITLE
DTS-HD HRA Bitstream Problem

### ISSUE THREAD

**Issue by mikounou** [Nevcairiel/LAVFilters#167] opened 2017-10-10 09:52 UTC
Hello,

I can't bitstream DTS-HD HRA.

My reveiver (Onkyo RZ900) display only DTS but no sound.

I have tested many things, change all options in Lav Filters, but no luck
I am forced to uncheck each time the bitstream to activate the PCM conversion...

No problem with other (Dolby Digital +, TrueHD, DTS or DTS-HD MA, DTS:X).

Thanks in advance

My config :
Windows 10 (latest update)
NVIDIA GTX 1070 (latest NVIDIA drivers)
Onkyo TX-RZ900 (latest firmware)
Latest MPC HC (nightly build)

**Comment by Nevcairiel** [comment] 2017-10-10 10:02
Not all receivers, specifically Onkyo, seem to support DTS-HD HRA properly. There is nothing I can do about that.

**Comment by mikounou** [comment] 2017-10-10 11:08
Thank you for your reply,
I called the suport onkyo but as long as it works with a classic BD Player, it's not their problem...

Would it be possible to separate the HRA from the DTS-HD option in the lavaudio GUI ?
It would be great to be able to automatically decode the HRA and bistreaming the MA without change the option.

**Comment by icemanfrance** [comment] 2017-10-26 15:17
Hi.
I'm french.
I've the same probleme with DTS HRA with Onkyo TX 646. With a pS3, It's ok. But with my pc, dts-hra become dts (passthrough with MPC hc LAv or Ffdshow). I can read dts-Ma.
I've tried to disable passtrough to send signal decode but my Onkyo says PCM 2.0

would it be possible that the problem comes from windows 10 64b ?

**Comment by Mazwak** [comment] 2017-12-06 09:21
I think it is more likely an issue with the amp. I purchased an onkyo 676 lately, and it doesn't play DTS HRA either, I use Kodi on linux.

**Comment by Hummerman0rg** [comment] 2018-01-04 21:53
It's a problem with LAVFilters. PowerDVD can bitstream DTS-HD HR with the same file.

**Comment by Goforcereloaded** [comment] 2018-02-25 16:12
Hello,

I have the exact same problem with two new Denon AVR-X4400H and Denon AVR-X8500H (these are one of the best receiver). (it was working fine with a Marantz SR5010 or Denon AVR-X6200W)

**Can't bitstream DTS-HD HRA, the reveiver display only DTS with distorded sound at low volume.**

Tested it with latest W10, MPC HC, LAVFilter and with a GTX 980Ti and GTX 1080Ti.

Every other format are working fine : Dolby Digital, Dobly Digital Plus, Dolby TrueHD, Atmos, DTS, DTS HD MA, DTS:X ...

DTS HD HRA is working without any problem with Powerdvd 17 on the same PC or with bluray player/Xbox One/PS4 so the receiver is not the problem.

Maybe there's a problem with New receiver and DTS HD HR in LAVFilter ?

**Comment by TomCom205** [comment] 2018-02-26 18:08
Hi there,

same Problem here with DENON X2400H.

It's working if i unselect the "DTS-HD" unselect inside the settings.
Then the AVR shows DTS but at least it is playing and sounds correct but sure it doesn't show its DTS -HD HRA.

Would be nice if it can be fixed.

**Comment by Nevcairiel** [comment] 2018-02-26 19:16
Unless someone wants to donate a receiver which actually has this problem, I can't really do anything about this. Both my old Onkyo and the more recent Sony receivers I own process DTS-HD HRA fine.

**Comment by chros73** [comment] 2018-02-26 19:55
Can you upload somewhere a short 1 min sample? I can try it out with Yamaha RX-A830.

**Comment by Nevcairiel** [comment] 2018-02-26 20:36
If you feel like testing, here is a LAV version with a few tweaks:
https://files.1f0.de/tmp/LAVFilters-0.71.0-9-dtstest.exe

I havev no idea if it makes any difference, but its the only knobs I currently have to turn.

**Comment by Goforcereloaded** [comment] 2018-02-26 21:18
Thanks i will test it when I go home.

@chros73 Here's a sample file of 62Mo for DTS HD HR : https://1fichier.com/?4onqx64ymg

**Comment by vipz** [comment] 2018-02-26 22:59
Tested the sample on my Yamaha RX-A3060 / GTX 980 / W10 / MPC-BE, no issues

**Comment by chros73** [comment] 2018-02-27 10:05
The sample doesn't work for me neither of the following test cases using Yamaha RX-A830. Here's the full config:
MSI GE60-0NC(i73630QM,16GB,IntelHD4000(10.18.10.4653) + GeForceGT650m(2GB,v355.98) + muxless, 1920x1080@60Hz, Plextor M5M 256GB SSD, Win8.1x64 + MPC-BEx64 + LAV + MadVR) + Yamaha RX-A830 + LG 55LD650(1080p@24/25/60Hz)

Test cases (x64 versions):
- distorted sound, AVR displays "DTS Hi Res" :
  - MPC-HC 1.7.15 (lav 0.71.0) 
  - MPC-BE + lav 0.71.0
  - MPC-BE with built in source filter AND DTS audio decoder
- no sound at all, AVR displays "Decoder is off" :
  - MPC-BE + lav 0.71.0-0-dtstest

So, the test build worse than the release version in this regard.
This case is interesting: "MPC-BE with built in source filter AND DTS audio decoder" :
- since it's just a small chance that both splitters/decoders have the same bug, can the HDMI audio driver (Intel in my case) cause such an issue?

I didn't have time to test it with PotPlayer yet.

**Comment by Nevcairiel** [comment] 2018-02-27 10:52
I wouldn't be surprised if most non-commercial stuff behaves the same, many tend to "borrow" the things I do.

The test version apparently didn't work at all, so a new one is coming up here:
https://files.1f0.de/tmp/LAVFilters-0.71.0-10-dtstest2.exe

**Comment by Goforcereloaded** [comment] 2018-02-27 12:34
I tested the 2 test version of LAVFilters, on the dtstest2 there's no sound in DTS HD HR -> "Signal Unknown" on the receiver. (on the first dtstest, the signal was "PCM ZERO").

Microsoft need to fix it also on W10 because the "Movies & TV" app has the same problem too, can't bitstream DTS-HD HRA, the reveiver display only DTS with distorded sound at low volume but every others format are working.

Thanks for trying to resolve the issue with LAVFilter ^^

**Comment by Nevcairiel** [comment] 2018-02-27 12:52
If it happens with the Movies & TV app as well, its quite likely that its in fact a problem in Windows somewhere.

**Comment by chros73** [comment] 2018-02-27 14:40
> I wouldn't be surprised if most non-commercial stuff behaves the same, many tend to "borrow" the things I do.

:D
I'll test the 2nd build during the evening along with PotPlayer.

**Comment by Nevcairiel** [comment] 2018-02-27 14:42
Also make sure to not check the DTS-HD framing checkbox, it should probably never be used.

**Comment by chros73** [comment] 2018-02-27 18:49
> Also make sure to not check the DTS-HD framing checkbox

Thanks, it was/is off.

MPC-BE + LAVFilters-0.71.0-10-dtstest2: distorted sound, AVR displays "DTS Hi Res" 
So there's no change.

PotPlayer doesn't have any built-in DTS/DTS-HD decoder, so it used lavfilters:
- but it only passed through the dts core (which worked) not the DTS HRA, no matter what I set

**Comment by Nevcairiel** [comment] 2018-02-27 19:36
Then I am all out of ideas. There is no special handling in the specification for different DTS types, only choice you get is the bandwidth - which I tried to adjust in the test builds, in case its extra picky.

It may be an issue with the Microsoft audio renderers for all I know, which something like PowerDVD may not use. A lot of unknowns.

**Comment by Nevcairiel** [comment] 2018-03-03 17:27
The dtstest2 build used 96 kHz, but apparently that also didn't help.

**Comment by TomCom205** [comment] 2018-03-03 17:29
I'll check it give me a few min.

**Comment by TomCom205** [comment] 2018-03-03 17:37
Okay the LAVFilters-0.71.0-10-dtstest2.exe doesn't even show a Signal like DTS or something ... it stays in Stereo or whatever the last signal has bin.

**Comment by Sebastiii** [comment] 2018-03-24 14:05
Hi,

I will retry on my side too but DTS-HD HR was not working good on my side too (Harman AVR-355).
@Nevcairiel can you share experiment your change, maybe i can try by testing different thing and build filter ?
Still i remember having this bug for a long time and it was before win10 but will retry on my side :P

**Comment by Sebastiii** [comment] 2018-03-24 14:49
Ok tested on my HTPC rig, no sound with directshow filter (but OK with PowerDVD), AVR show DTS-HD HI RES 3 / 4 / .1 96 Khz from above sample.

**Comment by olizan74** [comment] 2018-03-27 16:13
hi everybody, sorry i'm belgian and it's not my native langage.
I have the same problem as you. My onkyo tx-nr656 doesn't play dts-hd hr.
it's seem a nvidia drivers problem. Here a chat with the nvidia support in french : 

Bonjour Olivier, 

Merci pour votre patience. 

Je reviens vers vous avec un message après avoir vérifié cette situation avec les développeurs. 

Ils ont confirmé que nos pilotes ne sont pas compatibles avec le DTS-HR. La cause du souci provient d'ici. 

Nous nous excusons pour tout inconvénient que cela peut causer ! 

Pour le moment on va laisser cette demande de service ouverte encore quelques jours, et dans le cas où vous avez d'autres questions pour nous, n'hésitez pas de revenir vers nous avec un message et on fera de notre mieux afin de vous porter assistance !

En vous remerciant pour votre coopération et compréhension, je vous souhaite une excellente journée ! 

Cordialement,
Georgiana
Service Clientèle NVIDIA

**Comment by Sebastiii** [comment] 2018-03-27 18:19
Thanks Olizan74 :)

**Comment by Goforcereloaded** [comment] 2018-03-27 19:21
There's no problem with Nvidia driver.

DTS HD HR is working without any problem with PowerDVD, the problem is within the Windows 10 audio renderer. (PowerDVD don't use it)

**Comment by Sebastiii** [comment] 2018-03-27 21:55
On my side for being testing this week-end to try to generate dump out, none working except PowerDVD in Vista / 7 / 8.1 / 10 on the same rig. So it seems to not be only Windows 10 audio renderer issue :)

**Comment by olizan74** [comment] 2018-03-28 05:58
Powerdvd have own drivers and bypass nvidia drivers.

**Comment by joecrowrev-2** [comment] 2018-04-01 12:27
Also fails using AMD audio drivers (with AMD GPU) and Media Portal, MCE-HC (both LAV external Filters) and MPC-BE (Internal Filters), so I don't see this as a specific Nvidia driver problem, has to be LAV or Windows

**Comment by Goforcereloaded** [comment] 2018-04-01 18:15
Yes, it has nothing to do with Nvidia driver or AMD driver since DTS HD HR is working fine with every receivers with the old version of DTS.

Powerdvd is using Nvidia driver and AMD driver for the sound.

It's a problem in Windows audio renderer with new receivers that has the new "DTS" firmware.

Windows 10 need to be updated and maybe after that, LAVFilter will need to be updated too.

DTS HD HR is working fine on every receivers using the "old" version of DTS. (DTS HD HR is working fine on Marantz SR X008 / X009 or Denon AVR X-X000 for example) (I tested the marantz/denon receivers, I don't have tested other brands)

DTS HD HR is not working with Marantz SR X012 or Denon AVR X-X400 with every software in W10, except PowerDVD 17/18.

If DTS HD HR is working on PowerDVD 17/18, it's because they already updated the software to work with new version of the DTS firmware.


I tested Geforce GTX 670 / GTX 780 / GTX 980 Ti, 1080 Ti, Titan V, RX VEGA 56 and RX VEGA 64 on these receivers : 

Marantz SR 5008/6008/7008/6009/7009 and Denon AVR X-2000/X-3000/X-4000 : DTS HD HR is working fine with all the gpu in every software on W8-10.

Marantz SR 5012/6012/7012/8012 and Denon AVR X-3400/X-4400/X-6400/X-8500 : DTS HD HR is not working on all gpu in every software on W8-10, except PowerDVD 17/18.

The nvidia driver or amd driver used was the same (latest) on every test, so the problem is in Windows, not the drivers.

I don't know if Windows dev are aware of the problem or not, we need to contact them : d

**Comment by Sebastiii** [comment] 2018-04-02 05:54
Hi :)
When you tell about the new "DTS" firmware, do you have any date ?
My receiver is not new Harman/Kardon AVR-355 and DTS-HD HR only works with PDVD (i have tested the V14) from Vista to Win10 (on Vista it wasn't working).

The latest firmware was from 2010 upgraded from RS232 interface (my receiver was bought in 2009).
So maybe the issue is here from a long time already :)

**Comment by Nevcairiel** [comment] 2018-04-02 08:05
My 2012 Pioneer plays everything  fine, so date definitely isn't the only concern. But I don't think I've heard complaints from anyone that uses a Pio, so maybe they're just immune.

**Comment by Nevcairiel** [comment] 2018-04-02 09:44
Here is another test build:
https://files.1f0.de/tmp/LAVFilters-0.71.0-20-dtstest3.exe

Thanks to Sebastiii for testing some settings on his receiver, hopefully it works for you other guys as well.

**Comment by Sebastiii** [comment] 2018-04-02 11:01
Hey :) thanks to you too, all is working now :)

**Comment by fairgift** [comment] 2018-04-02 11:01
Also confirm the issue: no DTS-HDHR audio. Every other format (DTS-HDMA, DTS:X) without problems.

I have a Denon X3200W, a 2015 model. It always showed the "DTS version 3.90.35.00" (whatever that means), but in early March an OTA upgrade raised the version to " 3.90.50.00". So Denon/DTS definitely have changed something.

DTS-HDHR still works from my Blu-ray disc player, the Ultra-HD disc player and the old NeoTV Media player. But not from windows 10 anymore (VLC3, Kodi Leia, DVDFab Player 5).

**Comment by Nevcairiel** [comment] 2018-04-02 11:03
Did you try the new test build?

**Comment by Sebastiii** [comment] 2018-04-02 11:03
@fairgift did you try the latest above installer ? (dtstest3)
Tested it under MPC-HC (using external filter ofc) and working on my side now :P

**Comment by olizan74** [comment] 2018-04-02 11:21
this filter works with kodi ?

**Comment by Hummerman0rg** [comment] 2018-04-02 11:40
Dtstest3 works on my setup, too. Full sound with DTS-HD HR and DTS:X (HR-Core).

Windows 10 Pro x64, GeForce 1050 Ti, Denon AVR-X1300W

**Comment by Sebastiii** [comment] 2018-04-02 11:41
@olizan74 if you use the Kodi dsfilter version it should works (i didn't test it, like i'm using MP), otherwise kodi dev need to adapt it ofc :)

**Comment by chros73** [comment] 2018-04-02 11:53
`dtstest3` doesn't work here with `DTS HD HR, Core - 1509.m2ts` sample using MPC-BE or MPC-HC with Yamaha RX-A830.
Here's the full config:
MSI GE60-0NC(i73630QM,16GB,IntelHD4000(10.18.10.4653) + GeForceGT650m(2GB,v355.98) + muxless, 1920x1080@60Hz, Plextor M5M 256GB SSD, Win8.1x64 + MPC-BEx64 + LAV + MadVR) + Yamaha RX-A830 + LG 55LD650(1080p@24/25/60Hz)

**Comment by Sebastiii** [comment] 2018-04-02 11:57
@chros73 are you sure the new filter from dtstest3 are used ?
Thanks.

**Comment by chros73** [comment] 2018-04-02 12:10
Yes, I checked in both: it read *0-20 .

**Comment by fairgift** [comment] 2018-04-02 12:43
Latest test build works for me now! Denon X3200W with latest firmware. Tested with MPC-HC and two Blu-rays (with a 5.1 and a 7.1 DTS-HDHR track).

Good job! What did you change?

Denon wrote in their changelog: "Improvement of DTS:X recognition and processing with specific discs".

**Comment by Nevcairiel** [comment] 2018-04-02 13:01
At least it seems to work with a much wider range of devices now, I call that a success.

**Comment by Nevcairiel** [comment] 2018-04-02 13:28
As an additional note, make sure you use a DirectSound audio output, not the WaveOut ones. I've been a lot of issues with the WaveOut variant.

**Comment by chros73** [comment] 2018-04-02 16:46
For the record, I used "System Default"/"Primary Sound Driver" in the "Internal Audio Renderer"/"MPC Audio Renderer" in both MPC-HC/BE (although they are different engines), but I don't think it's related.

**Comment by Goforcereloaded** [comment] 2018-04-02 17:45
@Nevcairiel 

I tested the version 0.71.0.25-git (with K-Lite Codec Pack and MPC HC 1.7.15.3) and DTS HD HR is now working without any problem with softwares using LAVFilter : ) 

Thanks !

I tested on Denon AVR X-3400H / X-6400H and the new X-8500H.

It works also on older Marantz and the newer Marantz SR8012. (So I think the fix is working on every Marantz/Denon up to 2018 models)

Now Microsoft need to put this fix in W10 directly : D (the W10 app "movies & tv" has the same problem)

**Comment by joecrowrev-2** [comment] 2018-04-02 17:53
DTStest3 works fine for me Denon x1200W now plays and displays DTS-HD HR with Media Portal and AMD RX 570 Win 10 1709 and everything at the latest updates.

**Comment by mikounou** [comment] 2018-04-02 19:55
Fixed for me too with the DTStest3 ! (Onkyo RZ900 with latest firmware)
A big thank you to everyone and especially to Nevcairiel !

**Comment by TomCom205** [comment] 2018-04-04 16:57
Fixed here to with DENON X2400H @ DTStest3.
Also working inside Kodi with external Filter activated.
Well Done !!!
Thank you!

**Comment by olizan74** [comment] 2018-04-04 17:09
Could you tell me which tuto you have for Kodi ?

**Comment by olizan74** [comment] 2018-04-05 05:36
it doesn't work for me on Onkyo 656 with the lav filter i or ext

**Comment by Sebastiii** [comment] 2018-04-05 05:43
@olizan74 try the nightly build and with it under MPC-HC (using external filter ofc) :P
You need to uncheck all internal filter in config 👍 
![image](https://user-images.githubusercontent.com/756229/38348932-03f5f076-38a5-11e8-8531-6a6e86f8ae88.png)

**Comment by olizan74** [comment] 2018-04-05 06:26
sorry, i use kodi

**Comment by Sebastiii** [comment] 2018-04-05 10:25
@olizan74 it's for testing to know if it works after that you can rules out for KODI :)

**Comment by olizan74** [comment] 2018-04-05 13:14
ok it works with mpc-hc.

**Comment by olizan74** [comment] 2018-04-05 13:28
but kodi doesn't work

**Comment by TomCom205** [comment] 2018-04-05 15:38
You may use kodi with DSPlayer and there you may use the LAV Filters i.e. as "Systemdefault"
Works well...

**Comment by Sebastiii** [comment] 2018-04-05 16:15
Yep i can confirm it too, if kodi use external filter 'DSPlayer' (so using latest LAV suite) it works :P
So thanks to @olizan74 to confirm that it works for you too with latest LAV and your AVR :)

Call it a success :)

**Comment by olizan74** [comment] 2018-04-06 07:40
sorry i have some trouble to configure kodi. Dsplayer must be to system default for audio render and internal filter or external filter ?

**Comment by olizan74** [comment] 2018-04-06 07:47
ok i have found the solution. System default for audio render but directsound merits.

**Comment by olizan74** [comment] 2018-04-06 08:40
i have a second problem. In administrator profil, all works ! but when i switch to user profil, there is a video problem. No hardware decoder found. the video is not in full screen mode but the sound works !
any idea to resolve this stuff ?

**Comment by Nevcairiel** [comment] 2018-04-06 08:41
This is not a Kodi support platform, please use the official support channel for Kodi DSPlayer.

**Comment by olizan74** [comment] 2018-04-06 08:42
ok thanks.

**Comment by mikounou** [comment] 2018-04-10 16:30
Unfortunately with this version DTStest3, the bitsream of dolby digital plus is broken for me.
The video is accelerated and the amp switches from Dolby Digtal + 5.1 to 7.1 every second
(MPC-HC + Windows 10 + Onkyo RZ900

Do you have the same problem?

**Comment by Nevcairiel** [comment] 2018-04-10 21:00
The DTS test build is not supposed to handle Dolby Digital Plus. Use one of the more recent nightly builds from https://files.1f0.de/lavf/nightly/, those include the DTS changes and full support for DD+ bitstreaming as well.

**Comment by mikounou** [comment] 2018-04-11 19:29
Thanks Nevcairiel !
Yes, with the more recent nighlty build, all is ok !

**Comment by agasi34** [comment] 2018-04-13 07:47
Hi everybody,
i've also same issue with my onkyo rz800 ... no sound when i play DTS HRA on Kodi (on my nvidia shield) but all other HD audio work very well.

Do you know if its possible to have kodi dsplayer version on my nvidia shield ( android kodi) ?
If it's possible, i could use last lavfilter nighlty build on my shield to play all DTS HRA.

**Comment by Nevcairiel** [comment] 2018-04-13 07:59
No, thats not possible. You would have to wait for Kodi to fix the issue.

**Comment by agasi34** [comment] 2018-04-13 08:07
Thx for your quick answer Nevcairiel

**Closed** 2018-06-03 18:10 UTC
Labels: audio, need feedback
