### ISSUE TITLE
memory leak using QuickSync HW Acceleration

### ISSUE THREAD

**Issue by LordCM** [Nevcairiel/LAVFilters#44] opened 2015-11-18 11:25 UTC
when using ILAVVideoSettings.SetHWAccel(LAVHWAccel.HWAccel_QuickSync), decoder leaves unreleased HDC handles. Im not sure, if the problem is in QuickSync (latest version) or in its initialization/deinitialization on LAV side.
RuntimeConfig settings have no effect on the leak.

problem orrurs, when you use LAV+QuckSync multiple times (like playing short spots/movies in a loop)

Call stack where the unreleased handles are created:
GDI32!CreateDCA( LPCSTR, LPCSTR, LPCSTR, const DEVMODEA * )
d3d9!Direct3DCreate9Ex() + 0x663 bytes
d3d9!Direct3DCreate9Ex() + 0x3e39 bytes
d3d9!Direct3DCreate9Ex() + 0x13b bytes
d3d9!Direct3DCreate9() + 0x25 bytes
[Unidentified frame(s)]
LAVVideo!CDecQuickSync::InitDecoder( enum AVCodecID,class CMediaType const * ) quicksync.cpp Line 361 + 0x5 bytes
LAVVideo!CDecodeThread::CreateDecoderInternal( class CMediaType const *,enum AVCodecID ) decodethread.cpp Line 464 + 0xd bytes
LAVVideo!CDecodeThread::ThreadProc( void ) decodethread.cpp Line 280
LAVVideo!CAMThread::InitialThreadProc( void * ) wxutil.cpp Line 124 + 0x8 bytes
LAVVideo!thread_start<unsigned int ( __stdcall* ) thread.cpp Line 115 + 0x2 bytes
KERNEL32!@BaseThreadInitThunk@12() + 0x24 bytes
ntdll!___RtlUserThreadStart@8() + 0x2f bytes
ntdll!__RtlUserThreadStart@8() + 0x1b bytes
[Skipped frame(s)]

**Comment by Nevcairiel** [comment] 2015-11-18 11:26
Probably a duplicate of Issue 39

**Closed** 2015-11-18 11:26 UTC
Labels: duplicate

**Comment by LordCM** [comment] 2015-11-18 11:29
memory footprint is bigger only by about 44bytes. this is not the case like in 39.
problem is only unreleased HDC handles, there are 2 handles unreleased after each init/deinit of QS decoder. after playling 5000 loops, app crashes as it reaches 10k limit in windows
maybe there is some deinitialization error on LAV side..

**Comment by Nevcairiel** [comment] 2015-11-18 11:34
Even if its a different issue, the same comment applies:

The QuickSync decoder is a third-party component, and not developed by myself. Either report it to the author directly (http://sourceforge.net/projects/qsdecoder/), or switch to DXVA2-CopyBack, which is the recommended HW decoding mode.

LAV properly calls the "create" method on the QS object, which is where this HDC is allocated according to your trace, and it calls the "destroy" method when appropriate.
