### ISSUE TITLE
Video Seek Freeze

### ISSUE THREAD

**Issue by Leinad4Mind** [Nevcairiel/LAVFilters#66] opened 2016-02-07 00:43 UTC
Hi there, I've been doing a lot of tests, And I found out that when I'm using LAV Video, I got freezes on some x264 videos on some parts of the video on seeking. If I change the video to MPC-HC Internal, even keeping LAV Audio and LAV Splitter. No more freezes. I've test the video on VLC and it play fine too. (I've CCCP installed)
I've tested changing seek options on MPC-HC, but nothing, I changed to Kawai codec, and the problem existed too. So I'm preety sure the culprit is Lav Video.
I've tested with all LAV Filters since: 0.60.1 till the last one 0.67, and in all versions the problem exist :/

With 0.58.2 -The freeze doesn't exist but it appears this bug: http://i.imgur.com/sJU9gnd.jpg
With 0.59.1.26 - The bug above is gone, but it begins the freezing, but it has a lot of freeze way more then on 0.60.1 above, since on 0.6x versions I just see 1 or 2 "keyframes" that freezes.

I though it could be about x264 settings. but I have 2 videos with the same settings, and the problem just exist in one of the videos -.- 

And I encoded an mp4, and the original one doesnt have the freezing. -.- But I I've many encodes of mines with the same settings and the problem doesn't exist. :s

If you need more information about this, please ask.

**Comment by Nevcairiel** [comment] 2016-02-07 07:55
Please provide a sample video that allows me to reproduce the problem, otherwise there isn't much I can do.

**Comment by Leinad4Mind** [comment] 2016-02-07 18:53
Ok, I'll try to create a sample of the video and see if the problem remains on the sample.

**Comment by Leinad4Mind** [comment] 2016-02-29 23:59
Here it is the sample: https://mega.nz/#!2EUA2bTB!fvTE_lEhBF91MmjY4ttWKnZdKOxpeTFmlw3L-rrVtCU

Go to 50 Seconds, you'll see the image to Freeze.

Best Regards

**Comment by Nevcairiel** [comment] 2016-03-01 10:23
From what I can tell, the mp4 is kinda "broken". Its sample index marks a keyframe at that point, but its not actually a keyframe - the next keyframe is only 6 seconds later, hence the delay.

**Comment by Nevcairiel** [comment] 2016-03-01 10:54
More accurately, its not marked as a keyframe, but as a random access point using a 'sbgp' atom. Its certainly possible the other demuxers you tested don't respect this atom at all.

**Comment by Leinad4Mind** [comment] 2016-03-04 00:04
So, is this a problem of the x264 version?

**Comment by Nevcairiel** [comment] 2016-03-04 00:31
Well whatever wrote this mp4 file set a random access point there, but I don't see any indication of one. No key frames, no recovery point SEI.

And no, these random access point entries can be very useful, not respecting them because of a few broken files (or one broken muxer, at that), is not a solution.

**Comment by Nevcairiel** [comment] 2016-03-14 12:13
Closing this issue as the file in question is "bad".

**Closed by Nevcairiel** 2016-03-14 12:13 UTC
Labels: bug, video

**Comment by Leinad4Mind** [comment] 2016-04-23 19:02
Hi there, just to say that I found the culprit of the freeze frame. I was using megui last version, I tried the dev version of megui and it solved. I've check that the problem was on the mp4box that was "broken".
About each frame not beeing seekable on LAV any idea how to solve that?
Thanks again!
